# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentic.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "agentic.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ragentic.proto\x12\x07\x61gentic"?\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x12\n\nsession_id\x18\x03 \x01(\t"W\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\nsession_id\x18\x04 \x01(\t2E\n\x0e\x41genticService\x12\x33\n\x04\x43hat\x12\x14.agentic.ChatRequest\x1a\x15.agentic.ChatResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agentic_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CHATREQUEST"]._serialized_start = 26
    _globals["_CHATREQUEST"]._serialized_end = 89
    _globals["_CHATRESPONSE"]._serialized_start = 91
    _globals["_CHATRESPONSE"]._serialized_end = 178
    _globals["_AGENTICSERVICE"]._serialized_start = 180
    _globals["_AGENTICSERVICE"]._serialized_end = 249
# @@protoc_insertion_point(module_scope)
