# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from shared.grpc_gen import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in analytics_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrends = channel.unary_unary(
            "/analytics.AnalyticsService/GetTrends",
            request_serializer=analytics__pb2.TrendsRequest.SerializeToString,
            response_deserializer=analytics__pb2.AnalyticsResponse.FromString,
            _registered_method=True,
        )
        self.GetSurge = channel.unary_unary(
            "/analytics.AnalyticsService/GetSurge",
            request_serializer=analytics__pb2.SurgeRequest.SerializeToString,
            response_deserializer=analytics__pb2.AnalyticsResponse.FromString,
            _registered_method=True,
        )
        self.GetRecommendations = channel.unary_unary(
            "/analytics.AnalyticsService/GetRecommendations",
            request_serializer=analytics__pb2.RecommendationsRequest.SerializeToString,
            response_deserializer=analytics__pb2.AnalyticsResponse.FromString,
            _registered_method=True,
        )
        self.GetPeakWindow = channel.unary_unary(
            "/analytics.AnalyticsService/GetPeakWindow",
            request_serializer=analytics__pb2.PeakWindowRequest.SerializeToString,
            response_deserializer=analytics__pb2.AnalyticsResponse.FromString,
            _registered_method=True,
        )


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSurge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPeakWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetTrends": grpc.unary_unary_rpc_method_handler(
            servicer.GetTrends,
            request_deserializer=analytics__pb2.TrendsRequest.FromString,
            response_serializer=analytics__pb2.AnalyticsResponse.SerializeToString,
        ),
        "GetSurge": grpc.unary_unary_rpc_method_handler(
            servicer.GetSurge,
            request_deserializer=analytics__pb2.SurgeRequest.FromString,
            response_serializer=analytics__pb2.AnalyticsResponse.SerializeToString,
        ),
        "GetRecommendations": grpc.unary_unary_rpc_method_handler(
            servicer.GetRecommendations,
            request_deserializer=analytics__pb2.RecommendationsRequest.FromString,
            response_serializer=analytics__pb2.AnalyticsResponse.SerializeToString,
        ),
        "GetPeakWindow": grpc.unary_unary_rpc_method_handler(
            servicer.GetPeakWindow,
            request_deserializer=analytics__pb2.PeakWindowRequest.FromString,
            response_serializer=analytics__pb2.AnalyticsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "analytics.AnalyticsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("analytics.AnalyticsService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrends(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/analytics.AnalyticsService/GetTrends",
            analytics__pb2.TrendsRequest.SerializeToString,
            analytics__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSurge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/analytics.AnalyticsService/GetSurge",
            analytics__pb2.SurgeRequest.SerializeToString,
            analytics__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRecommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/analytics.AnalyticsService/GetRecommendations",
            analytics__pb2.RecommendationsRequest.SerializeToString,
            analytics__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPeakWindow(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/analytics.AnalyticsService/GetPeakWindow",
            analytics__pb2.PeakWindowRequest.SerializeToString,
            analytics__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
