# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rental.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rental.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crental.proto\x12\x06rental\">\n\rProductsQuery\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\t\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"%\n\x10ProductsResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t\"$\n\x0fProductResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t2\x92\x01\n\rRentalService\x12?\n\x0cListProducts\x12\x15.rental.ProductsQuery\x1a\x18.rental.ProductsResponse\x12@\n\nGetProduct\x12\x19.rental.GetProductRequest\x1a\x17.rental.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rental_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTSQUERY']._serialized_start=24
  _globals['_PRODUCTSQUERY']._serialized_end=86
  _globals['_GETPRODUCTREQUEST']._serialized_start=88
  _globals['_GETPRODUCTREQUEST']._serialized_end=127
  _globals['_PRODUCTSRESPONSE']._serialized_start=129
  _globals['_PRODUCTSRESPONSE']._serialized_end=166
  _globals['_PRODUCTRESPONSE']._serialized_start=168
  _globals['_PRODUCTRESPONSE']._serialized_end=204
  _globals['_RENTALSERVICE']._serialized_start=207
  _globals['_RENTALSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
